apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: default
  labels:
    app: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: 238475938391.dkr.ecr.ap-south-1.amazonaws.com/devops-nodejs-k8s-cicd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "2.0.0"
            - name: APP_MESSAGE
              value: "Version 3 - Live Demo "
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ecr-secret
